namespace H265Player.Models;

public sealed record SkyStreamChannel(int Number, string Name, string Category);

public static class SkyStreamChannels
{
    public static readonly IReadOnlyList<SkyStreamChannel> All =
    [
        new(101, "BBC One", "Entertainment"),
        new(102, "BBC Two", "Entertainment"),
        new(103, "ITV1", "Entertainment"),
        new(104, "Channel 4", "Entertainment"),
        new(105, "Channel 5", "Entertainment"),
        new(106, "Sky One", "Entertainment"),
        new(107, "Sky Witness", "Entertainment"),
        new(108, "Sky Atlantic", "Entertainment"),
        new(109, "Sky Comedy", "Entertainment"),
        new(110, "Sky Documentaries", "Entertainment"),
        new(111, "Sky Crime", "Entertainment"),
        new(112, "Sky Arts", "Entertainment"),
        new(113, "Sky Nature", "Entertainment"),
        new(114, "Sky Sci-Fi", "Entertainment"),
        new(115, "Sky History", "Entertainment"),
        new(118, "BBC Three", "Entertainment"),
        new(119, "BBC Four", "Entertainment"),
        new(120, "U&Alibi", "Entertainment"),
        new(121, "U&Gold", "Entertainment"),
        new(122, "ITV2", "Entertainment"),
        new(123, "ITV3", "Entertainment"),
        new(124, "ITV4", "Entertainment"),
        new(125, "ITV Quiz", "Entertainment"),
        new(126, "E4", "Entertainment"),
        new(127, "More4", "Entertainment"),
        new(128, "5STAR", "Entertainment"),
        new(129, "5USA", "Entertainment"),
        new(130, "U&Dave", "Entertainment"),
        new(131, "U&W", "Entertainment"),
        new(132, "U&Drama", "Entertainment"),
        new(133, "U&Yesterday", "Entertainment"),
        new(134, "U&Eden", "Entertainment"),
        new(135, "Comedy Central", "Entertainment"),
        new(136, "Comedy Central Extra", "Entertainment"),
        new(137, "MTV", "Entertainment"),
        new(138, "Discovery", "Entertainment"),
        new(139, "TLC", "Entertainment"),
        new(140, "Investigation Discovery", "Entertainment"),
        new(141, "Animal Planet", "Entertainment"),
        new(142, "Crime + Investigation", "Entertainment"),
        new(143, "Sky History 2", "Entertainment"),
        new(144, "National Geographic", "Entertainment"),
        new(145, "Nat Geo Wild", "Entertainment"),
        new(146, "Discovery Turbo", "Entertainment"),
        new(147, "Discovery History", "Entertainment"),
        new(148, "Discovery Science", "Entertainment"),
        new(149, "Quest", "Entertainment"),
        new(150, "Quest Red", "Entertainment"),
        new(151, "DMAX", "Entertainment"),
        new(152, "Food Network", "Entertainment"),
        new(153, "Really", "Entertainment"),
        new(155, "True Crime", "Entertainment"),
        new(156, "Legend", "Entertainment"),
        new(157, "True Crime Xtra", "Entertainment"),
        new(158, "Sky Mix", "Entertainment"),
        new(159, "Challenge", "Entertainment"),
        new(163, "4seven", "Entertainment"),
        new(164, "E4 Extra", "Entertainment"),
        new(165, "5ACTION", "Entertainment"),
        new(166, "5SELECT", "Entertainment"),
        new(167, "GREAT! TV", "Entertainment"),
        new(169, "Blaze", "Entertainment"),
        new(170, "PBS America", "Entertainment"),
        new(171, "Together TV", "Entertainment"),
        new(172, "S4C", "Entertainment"),
        new(173, "BBC Scotland", "Entertainment"),
        new(174, "BBC Alba", "Entertainment"),
        new(201, "CBBC", "Kids"),
        new(202, "CBeebies", "Kids"),
        new(203, "Sky Kids", "Kids"),
        new(204, "Disney Jr", "Kids"),
        new(205, "Nickelodeon", "Kids"),
        new(206, "Nicktoons", "Kids"),
        new(207, "Nick Jr", "Kids"),
        new(208, "Nick Jr Too", "Kids"),
        new(209, "Cartoon Network", "Kids"),
        new(210, "Boomerang", "Kids"),
        new(211, "Cartoonito", "Kids"),
        new(212, "BabyTV", "Kids"),
        new(301, "Sky Cinema Premiere", "Movies"),
        new(302, "Sky Cinema Animation", "Movies"),
        new(303, "Sky Cinema Box Set", "Movies"),
        new(304, "Sky Cinema Family", "Movies"),
        new(305, "Disney+ Cinema", "Movies"),
        new(306, "Sky Cinema Action", "Movies"),
        new(307, "Sky Cinema Greats", "Movies"),
        new(308, "Sky Cinema Comedy", "Movies"),
        new(309, "Sky Cinema Thriller", "Movies"),
        new(310, "Sky Cinema Drama", "Movies"),
        new(311, "Sky Cinema Sci-Fi/Horror", "Movies"),
        new(312, "Film4", "Movies"),
        new(313, "Movies24", "Movies"),
        new(314, "Movies24+", "Movies"),
        new(316, "Legend Xtra", "Movies"),
        new(317, "GREAT! Action", "Movies"),
        new(318, "GREAT! Mystery", "Movies"),
        new(319, "GREAT! Romance", "Movies"),
        new(354, "Clubland TV", "Music"),
        new(355, "NOW 70s", "Music"),
        new(356, "NOW 80s", "Music"),
        new(357, "NOW 90s & 00s", "Music"),
        new(358, "NOW Rock", "Music"),
        new(401, "Sky Sports Main Event", "Sports"),
        new(402, "Sky Sports Premier League", "Sports"),
        new(403, "Sky Sports Football", "Sports"),
        new(404, "Sky Sports+", "Sports"),
        new(405, "Sky Sports Cricket", "Sports"),
        new(406, "Sky Sports Golf", "Sports"),
        new(407, "Sky Sports F1", "Sports"),
        new(408, "Sky Sports Tennis", "Sports"),
        new(409, "Sky Sports News", "Sports"),
        new(410, "Sky Sports Action", "Sports"),
        new(411, "Sky Sports Racing", "Sports"),
        new(412, "Sky Sports Mix", "Sports"),
        new(413, "TNT Sports 1", "Sports"),
        new(414, "TNT Sports 2", "Sports"),
        new(415, "TNT Sports 3", "Sports"),
        new(416, "TNT Sports 4", "Sports"),
        new(417, "GINX eSports", "Sports"),
        new(418, "MUTV", "Sports"),
        new(419, "LFCTV", "Sports"),
        new(493, "TNT Sports Ultimate", "Sports"),
        new(501, "Sky News", "News"),
        new(502, "BBC News", "News"),
        new(503, "BBC Parliament", "News"),
        new(504, "CNBC", "News"),
        new(505, "Bloomberg", "News"),
        new(506, "CNN", "News"),
        new(508, "TalkTV", "News"),
        new(509, "GB News", "News"),
        new(510, "Euronews", "News"),
        new(511, "NDTV 24x7", "News"),
        new(512, "France 24", "News"),
        new(601, "QVC", "Shopping"),
        new(602, "QVC Style", "Shopping"),
        new(603, "QVC Beauty", "Shopping"),
        new(604, "QVC Extra", "Shopping"),
        new(701, "Star Bharat", "International"),
        new(702, "Star Plus", "International"),
        new(703, "Star Gold", "International"),
        new(704, "Sony TV", "International"),
        new(705, "Sony MAX", "International"),
        new(706, "Sony SAB", "International"),
        new(707, "Sony MAX 2", "International"),
        new(708, "Colors", "International"),
        new(709, "Colors Rishtey", "International"),
        new(710, "Colors Gujarati", "International"),
        new(711, "B4U Movies", "International"),
        new(712, "B4U Music", "International"),
        new(713, "Zee Cinema", "International"),
        new(714, "Zee TV", "International"),
        new(716, "Sky News Arabia", "International"),
        new(720, "HUM News", "International"),
        new(721, "HUM Europe", "International"),
        new(722, "Geo News", "International"),
        new(723, "Geo TV", "International"),
        new(724, "ARY Digital", "International"),
        new(725, "New Vision", "International"),
        new(740, "PTC Punjabi", "International"),
        new(741, "Zee Punjabi", "International"),
        new(742, "Brit Asia", "International")
    ];

    public static IReadOnlyList<IGrouping<string, SkyStreamChannel>> Groups { get; } =
        All.GroupBy(channel => channel.Category).ToList();
}
