<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <Title>Home Sky Q Live Streaming Player</Title>
    <Product>Home Sky Q Live Streaming Player</Product>
    <Description>Secure low-latency live home Sky Q streaming and remote control over the internet.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

</Project>
